name: Deploy TFG API to Azure Container Apps

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/TfgApi

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable dynamic install for Azure CLI extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      - name: Install containerapp extension
        run: az extension add --name containerapp --upgrade

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t vprietosainf/tfgapi:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push vprietosainf/tfgapi:latest

      - name: Update Azure Container App (new image)
        run: |
          az containerapp update \
            --name tfgapi \
            --resource-group tfg-infra-rg \
            --image vprietosainf/tfgapi:latest
